# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mikel/cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mikel/cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mikel/cpp/CMakeFiles /home/mikel/cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mikel/cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named elfin_tp

# Build rule for target.
elfin_tp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 elfin_tp
.PHONY : elfin_tp

# fast build rule for target.
elfin_tp/fast:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/build
.PHONY : elfin_tp/fast

src/force_sensor.o: src/force_sensor.cpp.o

.PHONY : src/force_sensor.o

# target to build an object file
src/force_sensor.cpp.o:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/src/force_sensor.cpp.o
.PHONY : src/force_sensor.cpp.o

src/force_sensor.i: src/force_sensor.cpp.i

.PHONY : src/force_sensor.i

# target to preprocess a source file
src/force_sensor.cpp.i:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/src/force_sensor.cpp.i
.PHONY : src/force_sensor.cpp.i

src/force_sensor.s: src/force_sensor.cpp.s

.PHONY : src/force_sensor.s

# target to generate assembly for a file
src/force_sensor.cpp.s:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/src/force_sensor.cpp.s
.PHONY : src/force_sensor.cpp.s

src/image_consumer.o: src/image_consumer.cpp.o

.PHONY : src/image_consumer.o

# target to build an object file
src/image_consumer.cpp.o:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/src/image_consumer.cpp.o
.PHONY : src/image_consumer.cpp.o

src/image_consumer.i: src/image_consumer.cpp.i

.PHONY : src/image_consumer.i

# target to preprocess a source file
src/image_consumer.cpp.i:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/src/image_consumer.cpp.i
.PHONY : src/image_consumer.cpp.i

src/image_consumer.s: src/image_consumer.cpp.s

.PHONY : src/image_consumer.s

# target to generate assembly for a file
src/image_consumer.cpp.s:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/src/image_consumer.cpp.s
.PHONY : src/image_consumer.cpp.s

src/master.o: src/master.cpp.o

.PHONY : src/master.o

# target to build an object file
src/master.cpp.o:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/src/master.cpp.o
.PHONY : src/master.cpp.o

src/master.i: src/master.cpp.i

.PHONY : src/master.i

# target to preprocess a source file
src/master.cpp.i:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/src/master.cpp.i
.PHONY : src/master.cpp.i

src/master.s: src/master.cpp.s

.PHONY : src/master.s

# target to generate assembly for a file
src/master.cpp.s:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/src/master.cpp.s
.PHONY : src/master.cpp.s

src/robot_command.o: src/robot_command.cpp.o

.PHONY : src/robot_command.o

# target to build an object file
src/robot_command.cpp.o:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/src/robot_command.cpp.o
.PHONY : src/robot_command.cpp.o

src/robot_command.i: src/robot_command.cpp.i

.PHONY : src/robot_command.i

# target to preprocess a source file
src/robot_command.cpp.i:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/src/robot_command.cpp.i
.PHONY : src/robot_command.cpp.i

src/robot_command.s: src/robot_command.cpp.s

.PHONY : src/robot_command.s

# target to generate assembly for a file
src/robot_command.cpp.s:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/src/robot_command.cpp.s
.PHONY : src/robot_command.cpp.s

src/robot_control.o: src/robot_control.cpp.o

.PHONY : src/robot_control.o

# target to build an object file
src/robot_control.cpp.o:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/src/robot_control.cpp.o
.PHONY : src/robot_control.cpp.o

src/robot_control.i: src/robot_control.cpp.i

.PHONY : src/robot_control.i

# target to preprocess a source file
src/robot_control.cpp.i:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/src/robot_control.cpp.i
.PHONY : src/robot_control.cpp.i

src/robot_control.s: src/robot_control.cpp.s

.PHONY : src/robot_control.s

# target to generate assembly for a file
src/robot_control.cpp.s:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/src/robot_control.cpp.s
.PHONY : src/robot_control.cpp.s

src/robot_kinematics.o: src/robot_kinematics.cpp.o

.PHONY : src/robot_kinematics.o

# target to build an object file
src/robot_kinematics.cpp.o:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/src/robot_kinematics.cpp.o
.PHONY : src/robot_kinematics.cpp.o

src/robot_kinematics.i: src/robot_kinematics.cpp.i

.PHONY : src/robot_kinematics.i

# target to preprocess a source file
src/robot_kinematics.cpp.i:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/src/robot_kinematics.cpp.i
.PHONY : src/robot_kinematics.cpp.i

src/robot_kinematics.s: src/robot_kinematics.cpp.s

.PHONY : src/robot_kinematics.s

# target to generate assembly for a file
src/robot_kinematics.cpp.s:
	$(MAKE) -f CMakeFiles/elfin_tp.dir/build.make CMakeFiles/elfin_tp.dir/src/robot_kinematics.cpp.s
.PHONY : src/robot_kinematics.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... elfin_tp"
	@echo "... src/force_sensor.o"
	@echo "... src/force_sensor.i"
	@echo "... src/force_sensor.s"
	@echo "... src/image_consumer.o"
	@echo "... src/image_consumer.i"
	@echo "... src/image_consumer.s"
	@echo "... src/master.o"
	@echo "... src/master.i"
	@echo "... src/master.s"
	@echo "... src/robot_command.o"
	@echo "... src/robot_command.i"
	@echo "... src/robot_command.s"
	@echo "... src/robot_control.o"
	@echo "... src/robot_control.i"
	@echo "... src/robot_control.s"
	@echo "... src/robot_kinematics.o"
	@echo "... src/robot_kinematics.i"
	@echo "... src/robot_kinematics.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

